### ISSUE TITLE
Is it possible to source code convert, like Python 2to3 ?

### ISSUE THREAD

**Issue by a500-app** [pyos/dg#6]
Is it possible to source code convert, like Python 2to3 ?
If it is possible to save as Python code, It may be run on PyPy 3.2 or Python 2.7.
Or Julialang version - dg.

**Comment by pyos** [comment]
Not really.  It's possible, but bytecode is way more flexible than source code and AST, so it'd be hard to replicate the exact semantics in pure Python code. Even in some simple cases is may lead to a huge increase in code size. Here's an example:

```dg
(namespace !! 'something') argument (argument + 1) $ except
  err => get_third_argument 'something_else'
  err :: IOError and err.errno == 13 => 'permission denied'
```

Simple enough: get a function from a dictionary, then call it with three arguments, the third of which is returned by a function which may fail. Unfortunately, try-except is an expression in Python, so you'd have to put it before the function call; and since the order of evaluation is important in an imperative language (and `argument` may be a global variable that `get_third_argument` changes), you'd have to calculate everything else before the call, too:

```python
_func = namespace['something']
_arg1 = argument
_arg2 = argument + 1
try:
    _arg3 = get_third_argument('something_else')
except IOError as err:
    if err.errno != 13:
        raise
    _arg3 = 'permission denied'
_func(_arg1, _arg2, _arg3)
```

And then there are things like the lazy evaluation of arguments to `or`/`and`. Just ask [the guys over at hy](https://github.com/hylang/hy/issues/766) - their compiler emits AST, and the distinction between expressions and statements gives them some trouble.

>PyPy 3.2

It's actually possible to run dg (with slight modifications) on PyPy 3.2, since it uses the same bytecode as CPython 3.2. The main problem is the incompatibility of the standard library; most notably, you'd have to reimplement the whole module import subsystem from scratch because the code Python itself uses to find modules was not public before 3.3 (which is the first version to use [importlib](https://docs.python.org/3/library/importlib.html).)
