### ISSUE TITLE
Using tabs instead of spaces breaks multiple features

### ISSUE THREAD

**Issue by XertroV** [pyos/dg#7]
Please consider the following examples. They were demonstrated on a Win7 x64 OS.

```
# class declaration
# using 2 spaces for indentation
ShibaInu = subclass object metaclass: type where
  __init__ = self name ->
    self.name = name

# using 1 tab for indentation
ShibaInu = subclass object metaclass: type where
	__init__ = self name ->
		self.name = name
```

The second declaration fails with `NameError: name 'name' is not defined`

Or this: (which requires copying into a file and running with `python -m dg`

```
# file1.dg
count = start: 1 ->
  yield start
  yield from $ count start: (start + 1)
print 'hi'
```

```
# file2.dg
count = start: 1 ->
	yield start
	yield from $ count start: (start + 1)
print 'hi'
```

My results are:
```
PS C:\Users\user\tmp> python -m dg .\file1.dg
hi
PS C:\Users\user\tmp> python -m dg .\file2.dg
PS C:\Users\user\tmp> python -m dg .\file1.dg
hi
```

There is nothing returned when attempting to run `file2.dg` and it silently dies.

Two naive solutions:
* tab detection along side spaces for indentation
* warning on running if a tab character is detected with its location, then the user can decide if it's relevant

**Comment by pyos** [comment]
Ah, right, that's because the parser only acceps spaces for indentation, so the first tab and everything after it are considered useless whitespace and skipped completely. I'd rather not allow tabs as indentation (that's not a good style, is it?), so I guess throwing a syntax error whenever a tab is encountered in indentation should fix this. Sounds good?
