### ISSUE TITLE
Do enums work?

### ISSUE THREAD

**Issue by MadcapJake** [pyos/dg#9]
I can't seem to translate a Python enum to dg.  Let me know if I am just missing the proper way of handling this.

Here's the python example from the [docs](https://docs.python.org/3/library/enum.html):
```python
from enum import Enum

class Shake(Enum):
    vanilla = 7
    chocolate = 4
    cookies = 9
    mint = 3

 for shake in Shake:
     print(shake)
```

And here's what I assume that would be in dg:
```dg
import '/enum/Enum'

Shake = subclass Enum where
    vanilla = 7
    chocolate  = 4
    cookies = 9
    mint = 3

print Shake                              #=> <enum 'Shake'>
print $ type Shake                       #=> <class 'enum.EnumMeta'>

print Shake.vanilla                      #=> 7
print $ Shake.vanilla :: Shake           #=> False *Should be true*

for shake in Shake =>
    print shake                          #=> *Doesn't print*
```
It seems that the `for` loop doesn't work on enums and `isinstance` compares `7`'s type (`int`) to Shake's type (`enum.EnumMeta`).

**Comment by pyos** [comment]
Yeah, that's because `EnumMeta` (the metaclass of `Enum`) replaces the class namespace with its own `dict` subclass and expects the class initialization code to use `__setitem__` to create attributes. dg, however, "cheats" it by calling `update` instead, which `_EnumDict` [does not reimplement](https://hg.python.org/cpython/file/3e9f4f3c7fa7/Lib/enum.py#l40).
